name: Create PR for Release Branch

on:
  push:
    branches:
      - 'release/*'

jobs:
  create-pr:
    name: Create Pull Request
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log branch name
        run: echo "Current branch is ${{ github.ref_name }}"

      # Step 2: Fetch all branches
      - name: Fetch all branches
        run: git fetch --all

      # Step 3: Create PR if it doesn't exist
      - name: Create Pull Request
        id: create_pr
        uses: repo-sync/pull-request@v2
        with:
          source_branch: ${{ github.ref_name }}
          destination_branch: main
          pr_title: "Merge ${{ github.ref_name }} into main"
          pr_body: "This pull request was created automatically by GitHub Actions."
          github_token: ${{ secrets.GH_PAT }}

      - name: Log PR URL
        run: echo "Pull Request URL ${{ steps.create_pr.outputs.pr_url }}"

  notify-email:
    name: Notify PR Status via Email
    needs: create-pr
    runs-on: ubuntu-latest

    steps:
      # Step 4: Send Email Notification
      - name: Send PR Status Email
        if: always() # This ensures the email is sent even if previous jobs fail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 587
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "Pull Request Status"
          to: mishra07.siddharth@gmail.com
          from: mishra07.siddharth@gmail.com
          body: |
            The pull request for branch ${{ github.ref_name }} has been created.
            Please review it here ${{ steps.create_pr.outputs.pr_url }}

